### PR TITLE
Update README to reflect current known issues.

### PR DESCRIPTION
**Pull request by pkajaba**
This PR is shedding some light on issues described here: https://github.com/openshiftio/openshift.io/issues/956

### CODE REVIEW

**Comment by pkajaba** [comment]
[test]

**Comment by pkajaba** [comment]
firehose fetcher seems to be not sending any new releases at this moment... So tests can't pass.

**Comment by pkajaba** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Pull request merged**
